Repository fga-eps-mds/2022-2-ez-docs, pull requests merged in 2022-12, with the labels that each got.

#40 docs: adiciona backlog do produto no README.md
  README.md
Labels: documentation

#50 Commands
  README.md
  src/__init__.py
  src/cmd/about.txt
  src/cmd/architecture.txt
  src/cmd/help.txt
  src/cmd/list.txt
  src/main.py
  src/modules/data_cleaning.py
  src/modules/usable.py
  tests_files/random.csv
  tests_files/random.html
  tests_files/random.xlsx
  tests_files/test.py
Labels: enhancement, feat

#62 Refactoring some files
  README.md
  src/README.md
  src/ez_docs/cmd/about.txt
  src/ez_docs/cmd/help.txt
  src/ez_docs/main.py
  src/ez_docs/modules/usable.py
Labels: documentation, enhancement, important, feat

#66 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#72 Initial sketch of progress bar
  src/ez_docs/main.py
  src/ez_docs/modules/usable.py
Labels: enhancement, feat
